name: "Org HTML Action"
description: "Action to create HTML files from Org files"
author: "Edmund Miller"
inputs:
  docs-dir:
    description: "Documentation Directory"
    required: true
    default: "docs"
outputs:
  output-dir:
    description: "Output Directory"
    required: true
    default: "public"
  output-type:
    description: "Type of output files"
    default: "html"

runs:
  using: "node12"
  main: "dist/index.js"
